profile:
  production: false

server:
  hostname: localhost
  port: 8080

datasource:
  user: gokeeperapp
  password: FWCRDJzp4G24AA
  host: localhost:5432
  database: gokeeper
  max-open-connections: 12
  connection-lifetime: 60

authentication:
  issuer: gokeeper
  jwt-signing-key: ENwJsa2nm674seV6
  jwt-duration-in-minutes: 30
