version: '3'
services:
  gokeeper:
    network_mode: host
    container_name: gokeeper
    build:
      context: ../../
      dockerfile: support/docker/server/Dockerfile
    depends_on:
      - "gokeeper-database"
  gokeeper-database:
    network_mode: host
    container_name: gokeeper-database
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: gokeeper
      POSTGRES_USER: gokeeperapp
      POSTGRES_PASSWORD: FWCRDJzp4G24AA
    volumes:
      - ./../database/postgres/migration/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/1-init.sql
  gokeeper-ui:
    network_mode: host
    container_name: gokeeper-ui
    build:
      context: ../../
      dockerfile: support/docker/client/Dockerfile
    depends_on:
      - "gokeeper"